# File Tree: helion-ai

**Generated:** 4/13/2026, 11:14:28 PM
**Root Path:** `d:\programs\helion-ai`

```
├── frontend-web
│   ├── public
│   │   ├── index (1) (1).html
│   │   └── index.html
│   ├── src
│   │   ├── components
│   │   │   ├── Navbar.css
│   │   │   └── Navbar.js
│   │   ├── pages
│   │   │   ├── Dashboard.css
│   │   │   ├── Dashboard.js
│   │   │   ├── Demo.css
│   │   │   ├── Demo.js
│   │   │   ├── Landing.css
│   │   │   ├── Landing.js
│   │   │   ├── Plans.css
│   │   │   ├── Plans.js
│   │   │   ├── Register.css
│   │   │   └── Register.js
│   │   ├── App.js
│   │   ├── index.css
│   │   └── index.js
│   ├── README.md
│   ├── package.json
│   └── vercel.json
├── gigshield-backend
│   ├── db
│   │   ├── schema.sql
│   │   └── supabase.js
│   ├── middleware
│   │   └── auth.js
│   ├── routes
│   │   ├── admin.js
│   │   ├── auth.js
│   │   ├── claims.js
│   │   ├── dashboard.js
│   │   ├── earnings.js
│   │   ├── health.js
│   │   ├── payouts.js
│   │   ├── plans.js
│   │   ├── premium.js
│   │   ├── profile.js
│   │   ├── subscribe.js
│   │   ├── subscriptions.js
│   │   ├── triggers.js
│   │   └── worker.js
│   ├── README.md
│   ├── db.js
│   ├── package-lock.json
│   ├── package.json
│   ├── schema.sql
│   └── server.js
├── gigshield-frontend
│   ├── assets
│   │   └── images
│   │       ├── favicon.png
│   │       ├── icon.png
│   │       ├── partial-react-logo.png
│   │       ├── react-logo.png
│   │       ├── react-logo@2x.png
│   │       ├── react-logo@3x.png
│   │       └── splash-icon.png
│   ├── src
│   │   ├── components
│   │   │   └── core
│   │   │       ├── AIInsightChip.tsx
│   │   │       ├── CustomInput.tsx
│   │   │       ├── GlassCard.tsx
│   │   │       ├── GradientButton.tsx
│   │   │       ├── StatusBadge.tsx
│   │   │       ├── SurfaceCard.tsx
│   │   │       └── ThemedText.tsx
│   │   ├── constants
│   │   │   └── Theme.ts
│   │   ├── screens
│   │   │   ├── ClaimHistoryScreen.tsx
│   │   │   ├── DashboardScreen.tsx
│   │   │   ├── EarningsScreen.tsx
│   │   │   ├── FileClaimScreen.tsx
│   │   │   ├── HealthScreen.tsx
│   │   │   ├── LoginScreen.tsx
│   │   │   ├── PayoutHistoryScreen.tsx
│   │   │   ├── PayoutSuccessScreen.tsx
│   │   │   ├── PlanDetailScreen.tsx
│   │   │   ├── PlanSelectionScreen.tsx
│   │   │   ├── ProfileScreen.tsx
│   │   │   ├── RegisterScreen.tsx
│   │   │   ├── TriggerViewScreen.tsx
│   │   │   └── WorkerActivityScreen.tsx
│   │   ├── services
│   │   │   └── api.ts
│   │   ├── store
│   │   │   └── store.ts
│   │   └── App.tsx
│   ├── .gitignore
│   ├── App.tsx
│   ├── README.md
│   ├── app.json
│   ├── package-lock.json
│   ├── package.json
│   └── tsconfig.json
├── ml-service
│   ├── app
│   │   ├── data
│   │   │   ├── process_data.py
│   │   │   └── rainfall.csv
│   │   ├── model
│   │   │   ├── encoder.pkl
│   │   │   ├── model.pkl
│   │   │   ├── predict.py
│   │   │   └── train.py
│   │   ├── services
│   │   │   └── weather.py
│   │   ├── utils
│   │   │   ├── city_mapper.py
│   │   │   └── encoder.py
│   │   └── config.py
│   ├── data
│   │   └── data.csv
│   ├── main.py
│   ├── requirements.txt
│   └── test_api.py
├── .gitignore
├── README.md
└── filetree.litcoffee
```

---

_Generated by FileTree Pro Extension_
